<!DOCTYPE html>
<html lang="ja-JP">
<head>
<!-- Global Site Tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-620926-3"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments)};
  gtag('js', new Date());

  gtag('config', 'UA-620926-3');
</script>

<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="../../../style.css">
<link rel="stylesheet" href="../../../syntax-highlight.css">
<link rel="icon" type="image/png" href="../../../rurema.png">

<link rel="canonical" href="https://docs.ruby-lang.org/ja/latest/method/Kernel/m/fail.html">

<title>Kernel.#fail (Ruby 2.4.0 リファレンスマニュアル)</title>
<meta name="description" content="例外を発生させます。
発生した例外は変数 [[m:$!]] に格納されます。また例外が
発生した時のスタックトレースは変数 [[m:$@]] に格納され
ます。発生した例外は rescue 節で捕捉できます。">
<script src="../../../script.js"></script>
</head>
<body>


<script type="application/ld+json">
{"@context":"http://schema.org","@type":"BreadcrumbList","itemListElement":[{"@type":"ListItem","item":"https://docs.ruby-lang.org/ja/latest/doc/index.html","name":"Ruby 2.4.0 リファレンスマニュアル","position":1},{"@type":"ListItem","item":"https://docs.ruby-lang.org/ja/latest/library/index.html","name":"ライブラリ一覧","position":2},{"@type":"ListItem","item":"https://docs.ruby-lang.org/ja/latest/library/_builtin.html","name":"組み込みライブラリ","position":3},{"@type":"ListItem","item":"https://docs.ruby-lang.org/ja/latest/class/Kernel.html","name":"Kernelモジュール","position":4},{"@type":"ListItem","item":"https://docs.ruby-lang.org/ja/latest/method/Kernel/m/fail.html","name":"fail","position":5}]}
</script>

<header>
  <nav>
    <ol class="inline-breadcrumb-list">
      <li>
        <a href="../../../doc/index.html">Ruby 2.4.0 リファレンスマニュアル</a>
      </li>
      <li>
        <a href="../../../library/index.html">ライブラリ一覧</a>
      </li>
      <li>
        <a href="../../../library/_builtin.html">組み込みライブラリ</a>
      </li>
      <li>
        <a href="../../../class/Kernel.html">Kernelモジュール</a>
      </li>
      <li>
        fail 
      </li>
    </ol>
  </nav>
</header>


<h1>module function Kernel.#fail</h1>
<dl class="methodlist">

<dt class="method-heading" id="M_FAIL"><code>raise -&gt; ()</code><span class="permalink">[<a href="../../../method/Kernel/m/fail.html">permalink</a>][<a href="https://docs.ruby-lang.org/en/2.4.0/Kernel.html#method-c-fail">rdoc</a>]</span></dt>
<dt class="method-heading"><code>fail -&gt; ()</code></dt>
<dt class="method-heading"><code>raise(message, cause: $!) -&gt; ()</code></dt>
<dt class="method-heading"><code>fail(message, cause: $!) -&gt; ()</code></dt>
<dt class="method-heading"><code>raise(error_type, message = nil, backtrace = caller(0), cause: $!) -&gt; ()</code></dt>
<dt class="method-heading"><code>fail(error_type, message = nil, backtrace = caller(0), cause: $!) -&gt; ()</code></dt>
<dd class="method-description">
<p>
例外を発生させます。発生した例外は変数 <a href="../../../method/Kernel/v/=21.html">$!</a> に格納されます。また例外が発生した時のスタックトレースは変数 <a href="../../../method/Kernel/v/=40.html">$@</a> に格納されます。発生した例外は rescue 節で捕捉できます。
</p>
<p>
引数無しの場合は、同スレッドの同じブロック内で最後に rescue された例外オブジェクト (<a href="../../../method/Kernel/v/=21.html">$!</a>) を再発生させます。そのような例外が存在しないが自身は捕捉されている時には例外 <a href="../../../class/RuntimeError.html">RuntimeError</a> を発生させます。
</p>
<pre>
begin
  open(&quot;nonexist&quot;)
rescue
  raise   #=&gt; `open': No such file or directory - &quot;nonexist&quot; (Errno::ENOENT)
end
</pre>
<p>
引数を渡した場合は、例外メッセージ message を持った error_type の示す例外(省略時 RuntimeError)を発生させます。
</p>
<p>
error_type として例外ではないクラスやオブジェクトを指定した場合、そのオブジェクトの exception メソッドが返す値を発生する例外にします。その際、exception メソッドに引数として変数 message を渡すことができます。
</p>
<dl>
<dt class='method-param'>[PARAM] error_type:</dt>
<dd>
発生させる例外を例外クラスまたは例外クラスのインスタンスで指定します。
</dd>
<dt class='method-param'>[PARAM] message:</dt>
<dd>
例外のメッセージとなる文字列です。
</dd>
<dt class='method-param'>[PARAM] backtrace:</dt>
<dd>
例外発生時のスタックトレースで、<a href="../../../method/Kernel/m/caller.html">Kernel.#caller</a> の戻り値と同じ形式で指定しなければいけません。
</dd>
<dt class='method-param'>[PARAM] cause:</dt>
<dd>
現在の例外(<a href="../../../method/Kernel/v/=21.html">$!</a>)の代わりに <a href="../../../method/Exception/i/cause.html">Exception#cause</a> に設定する例外を指定します。
</dd>
<dt>[EXCEPTION] TypeError:</dt>
<dd>
exception メソッドが例外オブジェクトを返さなかった場合に発生します。
</dd>
</dl>
<p>
例外の捕捉の例を示します。
</p>
<pre>
#例1
begin
  raise NameError,&quot;!!error!!&quot;
rescue ArgumentError =&gt; err
rescue NameError =&gt; err
rescue TypeError =&gt; err
ensure
  p err #=&gt; #&lt;NameError: !!error!!&gt;
end

#例2
def foo num
  print 'in method.'
  raise &quot;error!!&quot; if num &lt;= 9
rescue RuntimeError
  num += 10
  print 'in rescue.'
  retry
else
  print 'in else.'
ensure
  print &quot;in ensure.\n&quot;
end

foo(4) #=&gt; in method.in rescue.in method.in else.in ensure.

#例3
class MyException
  def exception(mesg=nil)
    SecurityError.new(mesg)
  end
end

begin
  raise MyException.new
rescue SecurityError
  p $! #=&gt; #&lt;SecurityError: SecurityError&gt;
end
</pre>
<p>
[SEE_ALSO] <a href="../../../method/Kernel/m/caller.html">Kernel.#caller</a>
</p>
</dd>


</dl>

<div id="footer">
  <a rel="license" href="https://creativecommons.org/licenses/by/3.0/">
    <img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by/3.0/88x31.png" />
  </a>

  フィードバックは<a href="https://github.com/rurema/doctree/issues/new" id="feedback-link">こちら</a>
  <script>if (window.URLSearchParams) { document.getElementById("feedback-link").search = new URLSearchParams({'body': document.location}); }</script></div>
</body>
</html>
